import os
import json
import base64
from dotenv import load_dotenv
import requests
import psycopg
from semantic_text_splitter import MarkdownSplitter
from openai import OpenAI


load_dotenv()


conn = psycopg.connect(
    host = os.getenv("DB_HOST"),
    dbname = os.getenv("DB_NAME"),
    user = os.getenv("DB_USER"),
    password = os.getenv("DB_PASSWORD"),
    port = os.getenv("DB_PORT")
)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
owner = os.getenv("GITHUB_OWNER")
repo = os.getenv("GITHUB_REPO")

openai_api_key = os.getenv("OPENAI_API_TOKEN")

#  Conexão com o Banco de dados & checagem/criação das tabelas)
def db_init(conn):

    cur = conn.cursor()

    cur.execute(
       """
       CREATE EXTENSION IF NOT EXISTS vector SCHEMA knowledge_base_ai;

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.pipeline (
       id serial4 NOT NULL,
       last_sync_date timestamp NULL,
       last_sync_sha text NOT NULL,
       CONSTRAINT pipeline_pkey PRIMARY KEY (id));

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.files (
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	     "path" TEXT UNIQUE NOT NULL,
	     "sha" TEXT NOT NULL,
	     PRIMARY KEY("id")
       );

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.chunks (
	     "file_id" INTEGER REFERENCES knowledge_base_ai.files("id") ON DELETE CASCADE,
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       "header" TEXT,
	     "content" TEXT NOT NULL,
	     "embedding" VECTOR(1536),
	     "chunk_index" INTEGER,
	     "content_tsv" TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED,
	     PRIMARY KEY("id"),
       UNIQUE (file_id, chunk_index)
       );
       """
    )

    cur.execute(
       """
       SELECT *
       FROM knowledge_base_ai.files
       """
    )


    data = cur.fetchall()
    conn.commit()
    if data == []:
     initial_sync = True
    else:
     initial_sync = False

    return initial_sync


## Puxar Arquivos (Sync Inicial) e armazenar commit atual
def initial_github_pull():

    url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/main?recursive=1"

    headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.json"
    }

    params={"ref": "main"}

    response = requests.get(
        url = url,
        headers = headers,
        params = params
    )

    response.raise_for_status()
    data = response.json()

    files = {}

    for item in data["tree"]:
     if item["type"] == "blob" and item["path"].endswith(".md") and item["path"] == "perfil/perfil.md":

        response = requests.get(
         url = item["url"],
         headers = headers,
         params = params
        )

        response.raise_for_status()
        encoded_content = response.json()
        content = base64.b64decode(encoded_content["content"]).decode("utf-8")

        files[item["path"]] = {"sha": item["sha"], "url": item["url"], "content": content}

    latest_commit_endpoint_url = f"https://api.github.com/repos/{owner}/{repo}/commits/main"

    headers = {
      "Authorization": f"Bearer {GITHUB_TOKEN}",
      "Accept": "application/vnd.github.json"
    }

    params={"ref": "main"}

    response = requests.get(
     url = latest_commit_endpoint_url,
     headers = headers,
     params = params
    )
    response.raise_for_status()
    sha_novo = response.json()["sha"]

    return files, sha_novo


def pull_github_diff(conn):
  files = {}
  cur = conn.cursor()

  cur.execute(
   """
   SELECT last_sync_sha
   FROM knowledge_base_ai.pipeline
   ORDER BY id DESC
   LIMIT 1
   """
   )
  last_sync_sha = cur.fetchone()[0]

  latest_commit_endpoint_url = f"https://api.github.com/repos/{owner}/{repo}/commits/main"

  headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.json"
  }

  params={"ref": "main"}

  response = requests.get(
   url = latest_commit_endpoint_url,
   headers = headers,
   params = params
  )
  response.raise_for_status()
  sha_novo = response.json()["sha"]

  diff_endpoint_url = f"https://api.github.com/repos/{owner}/{repo}/compare/{last_sync_sha}...{sha_novo}"

  response = requests.get(
   url = diff_endpoint_url,
   headers = headers,
   params = params
  )
  response.raise_for_status()

  diff = response.json()["files"]

  for diff_files in diff:
    url = f"https://api.github.com/repos/{owner}/{repo}/git/blobs/{diff_files["sha"]}"
    response = requests.get(
      url = url,
      headers = headers,
      params = params
     )

    response.raise_for_status()
    encoded_content = response.json()
    content = base64.b64decode(encoded_content["content"]).decode("utf-8")
    files[diff_files["filename"]] = {"sha": diff_files["sha"], "url": diff_files["blob_url"], "content": content}

  conn.commit()

  return files, sha_novo


def chunk(files):

 max_characters = 1500
 splitter = MarkdownSplitter(max_characters)


 for path, file_data in files.items():
   transformed_chunks = []
   last_seen_header = ""
   chunks = splitter.chunks(file_data["content"])
   for indice, chunk in enumerate(chunks):
     primeira_linha = chunk.splitlines()[0]  #extrair a primeira linha
     if primeira_linha.startswith(("#", "##", "###")): #Verificar se a primeira linha é um header
       last_seen_header = primeira_linha #se for, extrair e salvar
       if chunk == primeira_linha:
         pass
       else:
        transformed_chunks.append({"header": last_seen_header, "content": chunk.split("\n", 1)[1]})
     elif indice == 0 and chunk.strip().startswith("---"):
       pass
     else:
      transformed_chunks.append({"header": last_seen_header,"content": chunk})

   files[path]["chunks"] = transformed_chunks
 return files


def generate_embeddings(files):
  client = OpenAI(api_key=openai_api_key)

  for path, file_data in files.items():
    chunks_embeddings = []
    textos = []
    for c in file_data["chunks"]:
      textos.append(f"{c['header']}\n{c['content']}")

    response = client.embeddings.create(
    model="text-embedding-3-small",
    input=textos
    )
    embeddings = response.data
    for embedding_obj in embeddings:
     chunks_embeddings.append(embedding_obj.embedding)
    files[path]["chunks_embeddings"] = chunks_embeddings

  return files


def sync_to_postgres(files, conn):
  cur = conn.cursor()

  files_table_data = []

  for path, file_data in files.items():
   files_table_data.append((path, file_data["sha"]))


  cur.executemany(
   """
   INSERT INTO knowledge_base_ai.files (path, sha)
   VALUES (%s, %s)
   ON CONFLICT (path)
   DO UPDATE SET
   sha = EXCLUDED.sha
   """,
   files_table_data
  )

  all_paths = files.keys()
  cur.execute(
   """
   SELECT id, path
   FROM knowledge_base_ai.files
   WHERE path = ANY(%s)
   """,
   (list(all_paths),)
  )
  resultado = cur.fetchall()
  path_to_id = {}
  for file_id, path in resultado:
    path_to_id[path] = file_id

  chunks_table_data = []
  for path, file_data in files.items():
   for indice, chunk in enumerate(file_data["chunks"]):
    chunks_table_data.append((path_to_id[path], chunk["header"], chunk["content"], file_data["chunks_embeddings"][indice], indice))


  cur.executemany(
     """
     INSERT INTO knowledge_base_ai.chunks (file_id, header, content, embedding, chunk_index)
     VALUES (%s, %s, %s, %s, %s)
     ON CONFLICT (file_id, chunk_index)
     DO UPDATE SET
     header = EXCLUDED.header,
     content = EXCLUDED.content,
     embedding = EXCLUDED.embedding,
     chunk_index = EXCLUDED.chunk_index
     """,
     chunks_table_data
    )

  conn.commit()


def update_last_sync_sha(conn, sha_novo):
  cur = conn.cursor()

  last_sync_sha = (sha_novo,)

  cur.execute(
    """
    INSERT INTO knowledge_base_ai.pipeline (last_sync_sha, last_sync_date)
    VALUES (%s, now())
    """,
    last_sync_sha
  )

  conn.commit()


def rag_pipeline():
 initial_sync = db_init(conn)
 if initial_sync == True:
   files, sha_novo = initial_github_pull()
 else:
   files, sha_novo = pull_github_diff(conn)
 chunk(files)
 generate_embeddings(files)
 sync_to_postgres(files, conn)
 update_last_sync_sha(conn, sha_novo)

rag_pipeline()
