import os
import json
import base64
from dotenv import load_dotenv
import requests
import psycopg
from semantic_text_splitter import MarkdownSplitter
from openai import OpenAI

load_dotenv()

#Definir parametros da conexão com o banco de dados (Postgress)
conn = psycopg.connect(
    host = os.getenv("DB_HOST"),
    dbname = os.getenv("DB_NAME"),
    user = os.getenv("DB_USER"),
    password = os.getenv("DB_PASSWORD"),
    port = os.getenv("DB_PORT")
)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
owner = os.getenv("GITHUB_OWNER")
repo = os.getenv("GITHUB_REPO")

openai_api_key = os.getenv("OPENAI_API_TOKEN")

#  Conexão com o Banco de dados & checagem/criação das tabelas)
def db_init(conn):

    cur = conn.cursor()

    cur.execute(
       """
       CREATE EXTENSION IF NOT EXISTS vector SCHEMA knowledge_base_ai;

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.pipeline (
       id serial4 NOT NULL,
       last_sync_date timestamp NULL,
       last_sync_sha text NOT NULL,
       CONSTRAINT pipeline_pkey PRIMARY KEY (id));

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.files (
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	     "path" TEXT UNIQUE NOT NULL,
	     "sha" TEXT NOT NULL,
	     PRIMARY KEY("id")
       );

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.chunks (
	     "file_id" INTEGER,
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       "header" TEXT,
	     "content" TEXT NOT NULL,
	     "embedding" VECTOR(1536),
	     "chunk_index" INTEGER UNIQUE,
	     "content_tsv" TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED,
	     PRIMARY KEY("id")
       );

       ALTER TABLE knowledge_base_ai.chunks
       ADD FOREIGN KEY("file_id") REFERENCES knowledge_base_ai.files("id") ON DELETE CASCADE;
       """
    )

    conn.commit()


## Puxar Arquivos (Sync Inicial) e armazenar commit atual
def initial_github_pull(conn):

    url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/main?recursive=1"

    headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.json"
    }

    params={"ref": "main"}

    response = requests.get(
        url = url,
        headers = headers,
        params = params
    )

    response.raise_for_status()
    data = response.json()

    files = {}

    for item in data["tree"]:
     if item["type"] == "blob" and item["path"].endswith(".md") and item["path"] == "perfil/perfil.md":

        response = requests.get(
         url = item["url"],
         headers = headers,
         params = params
        )

        response.raise_for_status()
        encoded_content = response.json()
        content = base64.b64decode(encoded_content["content"]).decode("utf-8")

        files[item["path"]] = {"sha": item["sha"], "url": item["url"], "content": content}


    return files


def pull_github_diff():
 latest_commit_endpoint = f"repos/{owner}/{repo}/commits/main"
 diff_endpoint = f"repos/{owner}/{repo}/compare/{sha_antigo}{sha_novo}"
 return files


def chunk(files):

 max_characters = 1500
 splitter = MarkdownSplitter(max_characters)


 for path, file_data in files.items():
   transformed_chunks = []
   last_seen_header = ""
   chunks = splitter.chunks(file_data["content"])
   for indice, chunk in enumerate(chunks):
     primeira_linha = chunk.splitlines()[0]  #extrair a primeira linha
     if primeira_linha.startswith(("#", "##", "###")): #Verificar se a primeira linha é um header
       last_seen_header = primeira_linha #se for, extrair e salvar
       if chunk == primeira_linha:
         pass
       else:
        transformed_chunks.append(chunk)
     elif indice == 0 and chunk.strip().startswith("---"):
       pass
     else:
      chunk = f"{last_seen_header}\n" + chunk #se nao for, anexar o ultimo header como header
      transformed_chunks.append(chunk)

   files[path]["chunks"] = transformed_chunks
 return files



#sync_to_postgres(conn, files)

def generate_embeddings(files):
  client = OpenAI(api_key=openai_api_key)

  for path, file_data in files.items():
    chunks_embeddings = []
    response = client.embeddings.create(
    model="text-embedding-3-small",
    input=file_data["chunks"]
    )
    embeddings = response.data
    for embedding_obj in embeddings:
     chunks_embeddings.append(embedding_obj.embedding)
    files[path]["chunks_embeddings"] = chunks_embeddings

  return files



def sync_to_postgres(files, conn):
  cur = conn.cursor()

  files_table_data = []
  chunks_table_data = []

  for path, file_data in files.items():
   files_table_data.append((path), file_data["sha"])

  cur.executemany(
   """
   INSERT INTO knowledge_base_ai.files(
   path,
   sha,
   )

   VALUES (%s,)
   ON CONFLICT(path)
   DO UPDATE SET
   path, sha
   """
   files_table_data
  )

  conn.commit()


db_init(conn)
files = initial_github_pull(conn)
chunk(files)
generate_embeddings(files)
sync_to_postgres()




