import os
import json
import base64
from dotenv import load_dotenv
import requests
import psycopg
from semantic_text_splitter import MarkdownSplitter
from openai import OpenAI


load_dotenv()


GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
owner = os.getenv("GITHUB_OWNER")
repo = os.getenv("GITHUB_REPO")

openai_api_key = os.getenv("OPENAI_API_TOKEN")


# Database connection plus schema/table check and creation
def db_init(conn) -> bool:
    """
    Connects to the Database, checks tables and file data
    creates the schema, the vector extension and the tables on the initial sync
    """

    cur = conn.cursor()

    cur.execute(
        """
       CREATE SCHEMA IF NOT EXISTS knowledge_base_ai;

       CREATE EXTENSION IF NOT EXISTS vector SCHEMA knowledge_base_ai;

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.pipeline (
       id serial4 NOT NULL,
       last_sync_date timestamp NULL,
       last_sync_sha text NOT NULL,
       CONSTRAINT pipeline_pkey PRIMARY KEY (id));

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.files (
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	     "path" TEXT UNIQUE NOT NULL,
	     "sha" TEXT NOT NULL,
	     PRIMARY KEY("id")
       );

       CREATE TABLE IF NOT EXISTS knowledge_base_ai.chunks (
	     "file_id" INTEGER REFERENCES knowledge_base_ai.files("id") ON DELETE CASCADE,
	     "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       "header" TEXT,
	     "content" TEXT NOT NULL,
	     "embedding" VECTOR(1536),
	     "chunk_index" INTEGER,
	     "content_tsv" TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED,
	     PRIMARY KEY("id"),
       UNIQUE (file_id, chunk_index)
       );
       """
    )

    cur.execute(
        """
       SELECT *
       FROM knowledge_base_ai.files
       """
    )

    data = cur.fetchall()
    conn.commit()
    if data == []:
        initial_sync = True
    else:
        initial_sync = False

    return initial_sync


## Pull every file (initial sync) and store the current commit sha
def initial_github_pull():

    url = f"https://api.github.com/repos/{owner}/{repo}/git/trees/main?recursive=1"

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.json",
    }

    params = {"ref": "main"}

    response = requests.get(url=url, headers=headers, params=params)

    response.raise_for_status()
    data = response.json()

    files = {}

    for item in data["tree"]:
        if item["type"] == "blob" and item["path"].endswith(".md"):
            response = requests.get(url=item["url"], headers=headers, params=params)

            response.raise_for_status()
            encoded_content = response.json()
            content = base64.b64decode(encoded_content["content"]).decode("utf-8")

            files[item["path"]] = {
                "sha": item["sha"],
                "url": item["url"],
                "content": content,
            }

    latest_commit_endpoint_url = (
        f"https://api.github.com/repos/{owner}/{repo}/commits/main"
    )

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.json",
    }

    params = {"ref": "main"}

    response = requests.get(
        url=latest_commit_endpoint_url, headers=headers, params=params
    )
    response.raise_for_status()
    new_sha = response.json()["sha"]

    return files, new_sha


def pull_github_diff(conn):
    files = {}
    cur = conn.cursor()

    cur.execute(
        """
   SELECT last_sync_sha
   FROM knowledge_base_ai.pipeline
   ORDER BY id DESC
   LIMIT 1
   """
    )
    last_sync_sha = cur.fetchone()[0]

    latest_commit_endpoint_url = (
        f"https://api.github.com/repos/{owner}/{repo}/commits/main"
    )

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.json",
    }

    params = {"ref": "main"}

    response = requests.get(
        url=latest_commit_endpoint_url, headers=headers, params=params
    )
    response.raise_for_status()
    new_sha = response.json()["sha"]

    diff_endpoint_url = f"https://api.github.com/repos/{owner}/{repo}/compare/{last_sync_sha}...{new_sha}"

    response = requests.get(url=diff_endpoint_url, headers=headers, params=params)
    response.raise_for_status()

    diff = response.json()["files"]
    deleted_files = []

    for diff_files in diff:
        if diff_files["status"] == "renamed":
            deleted_files.append(diff_files["previous_filename"])
        if diff_files["status"] == "removed":
            deleted_files.append(diff_files["filename"])
        elif diff_files["filename"].endswith(".md"):
            url = f"https://api.github.com/repos/{owner}/{repo}/git/blobs/{diff_files['sha']}"
            response = requests.get(url=url, headers=headers, params=params)

            response.raise_for_status()
            encoded_content = response.json()
            content = base64.b64decode(encoded_content["content"]).decode("utf-8")
            files[diff_files["filename"]] = {
                "sha": diff_files["sha"],
                "url": diff_files["blob_url"],
                "content": content,
            }
        

    conn.commit()

    return files, new_sha, deleted_files

def clean_frontmatter(chunk):
    if chunk.count("---") >= 2:
        frontmatter_start = chunk.find("---")
        frontmatter_finish = chunk.find("---", frontmatter_start + 3)
        chunk_content = chunk[frontmatter_finish + 3:].strip()
        return chunk_content
    else:
        return chunk






def chunk(files):

    max_characters = 1500
    splitter = MarkdownSplitter(max_characters)

    for path, file_data in files.items():
        transformed_chunks = []
        last_seen_header = ""
        chunks = splitter.chunks(file_data["content"])
        for index, chunk in enumerate(chunks):
            first_line = chunk.splitlines()[0]  # take the first line
            if first_line.startswith(
                ("#", "##", "###")
            ):  # check whether the first line is a header
                last_seen_header = (
                    first_line  # if it is, keep it as the last seen header
                )
                if chunk == first_line:
                    pass
                else:
                    transformed_chunks.append(
                        {"header": last_seen_header, "content": chunk.split("\n", 1)[1]}
                    )
            elif index == 0 and chunk.strip().startswith("---"):
                frontmatter_clean_chunk = clean_frontmatter(chunk)
                if len(frontmatter_clean_chunk) <3:
                    pass
                else:
                    transformed_chunks.append(
                        {"header": last_seen_header, "content": frontmatter_clean_chunk}
                    )
            else:
                transformed_chunks.append(
                    {"header": last_seen_header, "content": chunk}
                )
        if transformed_chunks == []:
            pass
        else:
            files[path]["chunks"] = transformed_chunks
    return files


def generate_embeddings(files):
    client = OpenAI(api_key=openai_api_key)

    for path, file_data in files.items():
        if file_data.get("chunks"):
            chunks_embeddings = []
            texts = []
            for c in file_data["chunks"]:
                texts.append(f"{c['header']}\n{c['content']}")

            response = client.embeddings.create(
                model="text-embedding-3-small", input=texts
            )
            embeddings = response.data
            for embedding_obj in embeddings:
                chunks_embeddings.append(embedding_obj.embedding)
            files[path]["chunks_embeddings"] = chunks_embeddings

    return files


def sync_to_postgres(files, conn, deleted_files=None):
    cur = conn.cursor()

    files_table_data = []
    if deleted_files == None:
        deleted_files = []

    for path, file_data in files.items():
        files_table_data.append((path, file_data["sha"]))

    cur.executemany(
        """
   INSERT INTO knowledge_base_ai.files (path, sha)
   VALUES (%s, %s)
   ON CONFLICT (path)
   DO UPDATE SET
   sha = EXCLUDED.sha
   """,
        files_table_data,
    )

    all_paths = files.keys()
    cur.execute(
        """
   SELECT id, path
   FROM knowledge_base_ai.files
   WHERE path = ANY(%s)
   """,
        (list(all_paths),),
    )
    result = cur.fetchall()
    path_to_id = {}
    for file_id, path in result:
        path_to_id[path] = file_id

    chunks_table_data = []
    for path, file_data in files.items():
        for index, chunk in enumerate(file_data.get("chunks", [])):
            chunks_table_data.append(
                (
                    path_to_id[path],
                    chunk["header"],
                    chunk["content"],
                    file_data["chunks_embeddings"][index],
                    index,
                )
            )

    cur.executemany(
        """
     INSERT INTO knowledge_base_ai.chunks (file_id, header, content, embedding, chunk_index)
     VALUES (%s, %s, %s, %s, %s)
     ON CONFLICT (file_id, chunk_index)
     DO UPDATE SET
     header = EXCLUDED.header,
     content = EXCLUDED.content,
     embedding = EXCLUDED.embedding,
     chunk_index = EXCLUDED.chunk_index
     """,
        chunks_table_data,
    )

    cur.execute(
        """
     DELETE FROM knowledge_base_ai.files
     WHERE path = ANY(%s)
     """,
        (list(deleted_files),),
    )

    conn.commit()


def update_last_sync_sha(conn, new_sha):
    cur = conn.cursor()

    last_sync_sha = (new_sha,)

    cur.execute(
        """
    INSERT INTO knowledge_base_ai.pipeline (last_sync_sha, last_sync_date)
    VALUES (%s, now())
    """,
        last_sync_sha,
    )

    conn.commit()


def rag_pipeline():
    """
    Orchestrates the complete Rag pipeline, Retrieval -> Chunking -> Embedding -> Database
    """
    conn = None
    try:
        conn = psycopg.connect(
            host=os.getenv("DB_HOST"),
            dbname=os.getenv("DB_NAME"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD"),
            port=os.getenv("DB_PORT"),
        )
        initial_sync = db_init(conn)
        if initial_sync == True:
            files, new_sha = initial_github_pull()
            deleted_files = []
        else:
            files, new_sha, deleted_files = pull_github_diff(conn)
        chunk(files)
        generate_embeddings(files)
        sync_to_postgres(files, conn, deleted_files)
        update_last_sync_sha(conn, new_sha)
        response = "Sync successful"
    finally:
        if conn is not None:
            conn.close()
    return response
